version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5001"
    volumes:
      # Persist data directories
      - randwater-uploads:/app/uploads
      - randwater-backups:/app/backups
      - randwater-drafts:/app/drafts
      # Persist data files using named volumes to avoid host filesystem issues
      - randwater-data:/app/data
    environment:
      - FLASK_APP=randwater_calculator.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - randwater-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  randwater-uploads:
  randwater-backups:
  randwater-drafts:
  randwater-data:

networks:
  randwater-network:
    driver: bridge


